spring:
  application:
    name: Expense-tracker-web-app
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/expense_tracker_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope:
              - email
              - public_profile
            client-name: Facebook
jwt:
  secret: ${JWT_SECRET}
  access-expiration: 900000
  refresh-expiration: 604800000

app:
  frontend-url: ${FRONTEND_URL}